### ISSUE TITLE
URHO3D_HOME not found

### ISSUE THREAD

**Issue by knky-ru** [ArnisLielturks/Urho3D-Project-Template#1]
Hello!

What's wrong?

![image](https://user-images.githubusercontent.com/28824071/42728069-a83d6da8-87ba-11e8-9f51-91b4aeff19c3.png)

Home path is set correct. May be not?

![image](https://user-images.githubusercontent.com/28824071/42728074-d977245e-87ba-11e8-9851-59c627d19c0e.png)

Please help! Thanks

**Comment by ArnisLielturks** [comment]
You must build the Urho3D engine first. Build it in the same way how you would build this project.

**Comment by ArnisLielturks** [comment]
My environment config looks like this, Urho3D3 is the source directory that I pulled from github
![image](https://user-images.githubusercontent.com/7426555/42728373-4cf6fc6e-87c1-11e8-8702-46cdf9da89fd.png)

**Comment by knky-ru** [comment]
Thank you, that part solved, but here comes new one! Ohhhh..

Sorry for strange characters. 
![image](https://user-images.githubusercontent.com/28824071/42730577-8d81ee12-8800-11e8-8b55-8ec8a0781699.png)

What could it be? May be need full log?

**Comment by ArnisLielturks** [comment]
Kinda hard to tell but seems like your library is built for 32bit architecture, this sample - for 64bit or vice versa. Make sure that its the same!

**Comment by ArnisLielturks** [comment]
@knky-ru Did you manage to build it?
