### ISSUE TITLE
Many errors about no matching functions for calls...

### ISSUE THREAD

**Issue by JasonMiesionczek** [ArnisLielturks/Urho3D-Project-Template#12]
Which version of Urho 3D is this based on?

**Comment by ArnisLielturks** [comment]
@JasonMiesionczek Sample is built with the latest changes from the master branch. It might be few commits behind, but I tend to update it once in a while.

**Comment by ArnisLielturks** [comment]
Since we're on this, will update it now with the latest version.

**Comment by ArnisLielturks** [comment]
btw. The CI uses docker images from this repo: https://hub.docker.com/r/arnislielturks/urho3d
And the latest build was created 8 days ago with the changes what was in the Urho3D master branch. But noticed that not all CI builds use the latest version.
