### ISSUE TITLE
[URHO3D_LIB_TYPE SHARED] Setting RPATH in resulting binary

### ISSUE THREAD

**Issue by urnenfeld** [ArnisLielturks/Urho3D-Project-Template#14]
In the [UrhoBox](https://discourse.urho3d.io/t/rfc-the-urhobox-was-embedding-urho3d/5601) context, where games are suposed to link against the liburho3d shared lib.

Integrating the template binary into the image(as a first game), surprisingly the template cannot find the library while urho3d examples do.

Analyzing both elfs(template binary and a sample from urho3d) I realized that in the example there is an additional attribute(RPATH) in the elf which is helping to find the library:

```
$ arm-poky-linux-gnueabi-readelf 04_StaticScene -d

Dynamic section at offset 0x11bc4 contains 33 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libUrho3D.so.0]
 0x00000001 (NEEDED)                     Shared library: [libdl.so.2]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
 0x0000000f (RPATH)                      Library rpath: [$ORIGIN/../lib:$ORIGIN/../../lib:$ORIGIN/../lib/Urho3D:$ORIGIN/../../lib/Urho3D]
```
This extra stuff I would say in urho3d comes from [here](https://github.com/urho3d/Urho3D/blob/master/Source/CMakeLists.txt#L43)

Would it be reasonable to incorporate this in the template as well?
What would be the ideal cmake location?

**Comment by ArnisLielturks** [comment]
I guess it could be the CMake file in the root of this project. No objections from my side.

**Comment by urnenfeld** [comment]
Thanks, I will check on my side

**Comment by ArnisLielturks** [comment]
@urnenfeld Did you manage to fix this issue? I'm more than happy to include the fix in this project too.

**Comment by urnenfeld** [comment]
Hi @ArnisLielturks the [proposed fix](https://github.com/urnenfeld/meta-urho3D/blob/thud/recipes-games/Urho3D-Project-Template/files/001_add_rpath_subdirs.patch) worked:

However, I have not tested if that breaks some of your other builds... the main reason I did not created a pull request for you...

I can tell you [it worked](https://discourse.urho3d.io/t/rfc-the-urhobox-was-embedding-urho3d/5601/4?u=urnenfeld) for me... but how do we proceed?

**Comment by ArnisLielturks** [comment]
@urnenfeld applied your fix, works just as it should

**Comment by 100espressos** [comment]
This seemed promising but I do not recognize a path to my Urho library.

```
ldd ./ProjectTemplate 
        libUrho3D.so.0 => not found
```
```
readelf -d ./ProjectTemplate

Dynamic section at offset 0x1e6d60 contains 35 entries:
  Tag        Type                         Name/Value
 
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../lib:$ORIGIN/../../lib:$ORIGIN/../lib/Urho3D:$ORIGIN/../../lib/Urho3D:/usr/local/]
```
