### ISSUE TITLE
Error while linking on MSVC2017

### ISSUE THREAD

**Issue by CG-SS** [ArnisLielturks/Urho3D-Project-Template#2]
Version: 15.7.6
Urho3D version: Latest from the MASTER branch

The created .sln wrongly links both Urho3D.lib and Urho3D_d.lib for the Release build, creating conflicting links, since now you have 2 implementations of everything.

The solution is simple, on the Solution Explorer, right click 'EmptyProject' -> 'Properties' -> 'Linker' - > 'Additional Dependencies' and then remove the 'Urho3D_d.lib' for the Release build.

After that it compiles just fine.

**Comment by ArnisLielturks** [comment]
@CG-SS This is the line that causes this: https://github.com/ArnisLielturks/Urho3D-Empty-Project/blob/master/CMake/Modules/UrhoCommon.cmake#L932
