### ISSUE TITLE
Build for Android via Windows host Guide?

### ISSUE THREAD

**Issue by Kenji245** [ArnisLielturks/Urho3D-Project-Template#23]
im sorry if this is wrong place to ask, but i really have no idea how to build the project for android platform via windows host, in Urho3D i just simply import the whole Repo into android studio, how about this project? any guide? i'm not a pro though.

thanks in advance

**Comment by ArnisLielturks** [comment]
@Kenji245 sorry for delayed response, didn't notice this issue before. Unfortunately I don't have step-by-step tutorial about android builds on windows. But this sample uses the urho's build system as much as possible, currently I would say that the android builds are somewhat hacky. 


All the information about how it's built can be found here: 
https://github.com/ArnisLielturks/Urho3D-Project-Template/tree/master/BuildConfig/android specifically this file: 
https://github.com/ArnisLielturks/Urho3D-Project-Template/blob/master/BuildConfig/android/script.sh which is a step-by-step script for unix hosts. 

Script must be launched from the root directory of this sample. This file could be useful too, it shows how the scripts are launched for each of the build targets: https://github.com/ArnisLielturks/Urho3D-Project-Template/blob/master/.github/workflows/build.yml
