### ISSUE TITLE
Locale Duplicated Entry?

### ISSUE THREAD

**Issue by urnenfeld** [ArnisLielturks/Urho3D-Project-Template#28]
Hello,

I was working in the Spanish translation, realized FULLSCREEN entry is twice.

https://github.com/ArnisLielturks/Urho3D-Project-Template/blob/17f64c4f7eec602094acf5a6b1e24af573b9b8db/bin/Data/Translations/EN.json#L79

Intentional? I noted the Latvian version is left untranslated in the second instance...

**Comment by ArnisLielturks** [comment]
@urnenfeld that's a bug. There should be only one entry.

**Comment by ArnisLielturks** [comment]
And it's ok if some of the keys are missing, in that case the translation key is used instead.

**Comment by urnenfeld** [comment]
Ok, I will correct this one and fill the missing entries in a PR
