### ISSUE TITLE
I want to consulting if the project will continue?

### ISSUE THREAD

**Issue by ghost** [ArnisLielturks/Urho3D-Project-Template#29]

**Comment by ArnisLielturks** [comment]
@TsinElisha unfortunately the project is no longer maintained by me. I can answer any questions you have about it but I'm not planning to continue working on it. Also, @urnenfeld has been working with it and maybe he has a fork that has new features and bugfixes added.

**Comment by ghost** [comment]
Ok, Thanks for you answer!

**Comment by urnenfeld** [comment]
I am preparing a few PR for AudioManager and locales, not really relevant @ArnisLielturks would you be accepting PRs?

**Comment by ArnisLielturks** [comment]
@urnenfeld I would suggest moving this project to your profile. In that case I could archive this repo and add link to to your fork instead. Just so that people see that project is still ongoing.

**Comment by urnenfeld** [comment]
There is a [fork on my profile](https://github.com/urnenfeld/Urho3D-Project-Template) with such [commit](https://github.com/urnenfeld/Urho3D-Project-Template/commit/e8e236e705e52386836f8cb8118efda9e6c7f22c), the intention was to share the modifications I had on my integration.
You have all the merits of the work here, any decision is accepted :)

**Comment by ArnisLielturks** [comment]
@urnenfeld ok. I will update the repo a bit later when I get on a computer.

**Comment by ArnisLielturks** [comment]
@urnenfeld Added link to your repository in the readme. Btw I also think you need to import the wiki documentation from this repository into your own.  It might not be 100% up-to-date, but there is a lot of useful stuff there. Also, you could enable Github Actions for it too.

When that's done, will archive this repository. Feel free to do with this project whatever you like. 👍🏻

**Comment by urnenfeld** [comment]
> Btw I also think you need to import the wiki documentation from this repository into your own. It might not be 100% up-to-date, but there is a lot of useful stuff there.

True, There are also some chat conversations with you I may transcribe into a page :) 
I believe I managed to clone the wiki it properly, take a look

> you could enable Github Actions for it too.

Any action in particular you were thinking on?

**Comment by ArnisLielturks** [comment]
@urnenfeld I was thinking about the Github's built in CI - https://github.com/urnenfeld/Urho3D-Project-Template/actions
Wiki looks good, with that being said I'm moving this repo to archive! 👍🏻
