### ISSUE TITLE
Compatibility with Urho3D 1.7 / HEAD

### ISSUE THREAD

**Issue by urnenfeld** [ArnisLielturks/Urho3D-Project-Template#6]
Hello I have the Urho3D HEAD from mid Jan19,

Currently I can't build the template given:

https://github.com/ArnisLielturks/Urho3D-Project-Template/blob/4363d52aa4858d6c7ed80a458e112fcbbafbbe8a/Source/BaseApplication.cpp#L306

I can see this has been recently introduced to Urho3D HEAD, 
Just as confirmation, we need to update the engine?
Is there any simple workaround?

**Comment by ArnisLielturks** [comment]
@urnenfeld This sample works with the latest changes in the Urho3D master branch. 1.7 is very old version and I'm not planning to support it.

The line that you mentioned uses the new translation file format, I was using the old format few commits ago, you can try to build it with that. But as far as I know, others also were complaing that it doesn't work with the 1.7 version.

**Comment by geeb** [comment]
The sample compiles successfully on my win10 x64 laptop. Urho3d master synced yesterday. Only issues I've seen so far is that it doesn't load the Scene, gets stuck after Loading Images steps and the progress percentage is like 2148362%. I don't want to thread jack, plus I haven't debugged or messed with it more yet. If I can't figure it out I'll create a new issue.

**Comment by ArnisLielturks** [comment]
@geeb Try to delete the `https://github.com/ArnisLielturks/Urho3D-Project-Template/blob/master/bin/Data/Mods/LoadStepImitator.as` file and launch the sample. That could help. Also will test this out with the latest changes of the engine.

**Comment by ArnisLielturks** [comment]
@geeb Got the same error using latest Urho3D version. Will dig into this right away.

**Comment by ArnisLielturks** [comment]
@geeb And it's fixed. Forgot to initialize the progress value to 0 when construcing the `SceneManager`.

**Comment by geeb** [comment]
Sweet. I'll check it out when I get home. Thanks for the quick fix and thank you for the great work.

**Comment by ArnisLielturks** [comment]
@geeb My pleasure!

**Comment by urnenfeld** [comment]
@ArnisLielturks yep is totally understandable.
