### ISSUE TITLE
Build without LUA?

### ISSUE THREAD

**Issue by urnenfeld** [ArnisLielturks/Urho3D-Project-Template#8]
Hi, would it be reasonable to build the template with LUA/AS disabled?

The background of the question is that in my experiments, I had to disable LUA in the engine, Then currently I am evaluating bringing this template in...

**Comment by ArnisLielturks** [comment]
@urnenfeld At the moment the only place where script functionality is actually used is in these files: https://github.com/ArnisLielturks/Urho3D-Project-Template/tree/master/Source/Mods

And at the moment you can't explicitly disable the LUA and/or AS. But should be fine if you comment out everything related to scripts in these files OR you can remove ModLoader altogether from the project. ModLoader subsystem is registered in this file: https://github.com/ArnisLielturks/Urho3D-Project-Template/blob/master/Source/BaseApplication.cpp

PR to detect AS and LUA availability with preprocessor values are welcome!

**Comment by urnenfeld** [comment]
Hello @ArnisLielturks ,

I could build the template with just ifdeffing out the LUA parts. AS part has not been a conflict:

https://github.com/urnenfeld/meta-urho3D/blob/thud/recipes-games/Urho3D-Project-Template/files/000_remove_lua.patch

This is integrated in the build so it does not affect me anymore.

I am not yet fully into cmake, so I am not sure what would be the best approach. Can something like this like -DLUA_ENABLED be passed upon cmake invocation? (in such case I need to rework the patch) 

PS: You might be interested in: https://github.com/urnenfeld/meta-urho3D/blob/thud/classes/arnistemplate.bbclass

**Comment by ArnisLielturks** [comment]
Did the update with the help of cmake checks. PR here: https://github.com/ArnisLielturks/Urho3D-Project-Template/pull/9

**Comment by 100espressos** [comment]
Maybe this has resurfaced? I get link errors related to both `URHO3D_ANGELSCRIPT=0` and `URHO3D_LUA=0`..
